%% set parameters
wavelength = 1030;

% this is not used, but a copy of it will be made with the calib info
% generated by this script:
base_calib = 'C:\Users\holos\Documents\calibs\23-Jan-2025_Calib_1030.mat';

slmXrange = [0, 1];
slmYrange = [0, 1];
slmZrange = 0*[-0.2 0.2];

% discretization levels for each dimension:
numX = 31;
numY = 31;
numZ = 1;  % make this odd number

% make sure all odd:
assert(mod(numX,2)==1)
assert(mod(numY,2)==1)
assert(mod(numZ,2)==1)
%% setup SLM

[Setup ] = function_loadparameters2();
Setup.CGHMethod=2;
Setup.GSoffset=0;
Setup.verbose =0;

slm = get_slm(wavelength);

slm.stop();
slm.wait_for_trigger = 0;
slm.start();

slmCoords = [.4, .4, 0, 1];
[Holo, ~, ~ ] = function_Make_3D_SHOT_Holos( Setup,slmCoords );
slm.feed(Holo);

%% load powermeter reader
tpm = ThorlabsPowerMeter();
tpm.set_wavelength(wavelength);

disp('Turn on FS50, set FS50 parameters to something not crazy (e.g, a few mW)')
input('Press enter when ready: ')
%% create SLM coordinate meshgrid
x = linspace(slmXrange(1), slmXrange(2), numX);
y = linspace(slmYrange(1), slmYrange(2), numY);
z = linspace(slmZrange(1), slmZrange(2), numZ);

% [x,y,z] = meshgrid(x,y,z);
% x = x(:);
% y = y(:);
% z = z(:);

%% loop through SLM positions and record power
powers = zeros(numX, numY, numZ);
count = 1;
tic
for i = 1:numX
    for j = 1:numY
        for k = 1:numZ
            slmCoords = [x(i), y(j), z(k), 1]; % 0.
            [Holo, ~, ~ ] = function_Make_3D_SHOT_Holos( Setup,slmCoords );
            slm.feed(Holo);
            
            pause(.25)
            pwr = tpm.read();

            powers(i, j, k) = pwr;
            
            count = count + 1;

            time_per_iter = toc/count;
            disp(['Elapsed: ', num2str(toc), ' sec'])
            disp(['Remaining (est.): ', num2str((numX*numY*numZ-count)*time_per_iter), ' sec'])
            
            if numZ == 1
                figure(123)
                imagesc(powers)
                colorbar
            end
            
        end
    end
    i
end

%% save this calibration data:

load(base_calib)

DE_calib.slmXgrid = x;
DE_calib.slmYgrid = y;
DE_calib.slmZgrid = z;
DE_calib.powers = powers;

CoC.DE_calib = DE_calib;

save([base_calib(1:end-4), '_DE_calib.mat'], 'CoC')